# Generated by Django 5.0.1 on 2024-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_email_profile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('0', 'Brak'), ('1', 'Wysoki'), ('2', 'Średni'), ('3', 'Niski')], default='0', max_length=1)),
            ],
        ),
    ]
