# Generated by Django 5.0.1 on 2024-03-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('documentations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.TextField()),
                ('modification', models.TextField()),
                ('fixes', models.TextField()),
                ('photos', models.ImageField(upload_to='')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.machinedatabase')),
            ],
        ),
    ]
