# Generated by Django 4.2.6 on 2024-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_machinedatabase_documentations'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedatabase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinedatabase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
