# Generated by Django 5.0.1 on 2024-03-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_machinedatabase_description_machinedatabase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedatabase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
