# Generated by Django 4.2.6 on 2024-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_machinedatabase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedatabase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines_images/'),
        ),
        migrations.RemoveField(
            model_name='machinehistory',
            name='name',
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='name',
            field=models.ManyToManyField(to='base.machinedatabase'),
        ),
    ]
