# Generated by Django 4.2.6 on 2024-03-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_machinedatabase_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinehistory',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
