# Generated by Django 4.2.6 on 2024-03-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_machinehistory_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinehistory',
            name='name',
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.machinedatabase'),
        ),
    ]
