# Generated by Django 4.2.6 on 2024-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_machinehistory_name_machinehistory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinehistory',
            old_name='name',
            new_name='machine',
        ),
    ]
