# Generated by Django 4.2.6 on 2024-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_name_machinehistory_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinehistory',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinehistory',
            name='fixes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinehistory',
            name='modification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
