# Generated by Django 4.2.6 on 2024-03-12 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_alter_machinehistory_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinehistory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
