# Generated by Django 4.2.6 on 2024-03-14 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_machinechanges_machinefixes_machinemodifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinefixes',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='fixes_images/'),
        ),
        migrations.AlterField(
            model_name='machinemodifications',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='modifications_images/'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('line', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('0', 'Brak'), ('1', 'Wysoki'), ('2', 'Średni'), ('3', 'Niski')], default='0', max_length=1)),
                ('type_of_issue', models.CharField(blank=True, choices=[('0', 'Awaria'), ('1', 'Przezbrojenie')], max_length=1, null=True)),
                ('accepted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_issues', to=settings.AUTH_USER_MODEL)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authored_issues', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.machinedatabase')),
            ],
        ),
    ]
