# Generated by Django 4.2.6 on 2024-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_machinefixes_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
