# Generated by Django 4.2.6 on 2024-03-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_alter_issue_end_date_alter_issue_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='accepted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
