# Generated by Django 4.2.6 on 2024-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_forum_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
