# Generated by Django 4.2.6 on 2024-03-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_forum_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='active',
        ),
    ]
