# Generated by Django 4.2.6 on 2024-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_forum_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
