# Generated by Django 4.2.6 on 2024-03-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_forum_active'),
    ]

    operations = [
    ]
