# Generated by Django 4.2.6 on 2024-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='tag',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
